export const STORE_PRICES = "STORE_PRICES";
export const UPDATE_INGREDIENTS = "UPDATE_INGREDIENTS";
export const UPDATE_PRICE = "UPDATE_PRICE";
export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";